### ISSUE TITLE
Queries on Using Customised Controller on this Framework

### ISSUE THREAD

**Issue by lakshmikanth-nageswar** [BinghengNUS/LearningAgileFlight_SE3#3]
Hi, could anyone please clear these queries of mine:

- Where exactly in the code is the parameters of System Dynamics (Mass, Inertia, etc) is declared (numerical values)? and is the Dynamics used in training the same as PyBullet Crazyflie (Drone) Dynamics? And could you please tell how to discretise the dynamics (for complete non linear model and linearised dynamics about an equilibrium point)
- How to modify the training tasks say for hover, single set-point (regularisation) and tracking problem through this framework? and for visualisation of trained policy in pybullet as well. (how to modify the GateAviary and other scripts required to be modified?)
- This framework implies training on standalone without actual state and pose feedback from environment (please correct if I am wrong), in case we are intending to train policy with feedback from env what are the changes that has to be made?

I kindly request to clear my queries. Thank you!

**Comment by BinghengNUS** [comment]
Hi, the model parameters are default values used in the Dronesmodel class within the 'utils' file, different from the model in training. Within MPC, the discretization can vary, depending on the specific methods like RK4 or Forward Euler. For gym-pybullet-drone engine, you do not need to discretize the model by yourself. Please note that the learning framework proposed in this paper is applied to only the agile flight through narrow gates, other tasks may require a completely new/different framework.

**Comment by lakshmikanth-nageswar** [comment]
Thanks for the clarification!

Could you please tell if we can train the controller with feedback from Pybullet (Online training) or any way to train the controller and use it post for simulation for some learning aided Model Based control techniques. [maybe similar to your method]

**Comment by BinghengNUS** [comment]
Hi, closed-loop training using gym-pybullet-drone is possible, just like what we do for closed-loop control which takes the state from the siumaltor as feedback. At each step, you sample the system states from the simulator (environment), evaluate their performance with a reward, and then perform gradient-based training.
